Update dev environment to python 3.12 (#1509)
Fixes #1491 

# Description
Use python 3.12 in dev environment.

2 issues had to be resolved:
- There is an issue with the pytest 8.4.0 i.c.w. pytest cases. Therfor i
have pinned pytest until it gets resolved
(https://github.com/smarie/python-pytest-cases/issues/365)
- There was a racecondtion going on in the test_import_prj.py file.
Several tests were downloading the iMOD5_model.zip through pooch at the
same time. I resolved it by having the tests get the file by calling the
imod5_projectfile_data. This method has a filelock to prevent race
conditions

Original errors:
> ERROR test_formats\test_idf.py - AttributeError: 'MiniMetafunc' object
has no attribute '_params_directness'
> ERROR test_mf6\test_import_prj.py - PermissionError: [WinError 32] The
process cannot access the file because it is being used by another
process
> ERROR test_mf6\test_mf6_regrid_scheme.py - AttributeError:
'MiniMetafunc' object has no attribute '_params_directness'

# Checklist
<!---
Before requesting review, please go through this checklist:
-->

- [x] Links to correct issue
- [ ] Update changelog, if changes affect users
- [x] PR title starts with ``Issue #nr``, e.g. ``Issue #737``
- [ ] Unit tests were added
- [ ] **If feature added**: Added/extended example

---------

Co-authored-by: Sunny Titus <sunny.titus@deltares.nl>